version: "v2.27.0-desktop.2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: web
    ports:
      - '3000:80' # Map host port 3000 to container port 80
    volumes:
      - .:/apps/web # Only needed if you want to make changes and rebuild