version: "v2.27.0-desktop.2"
services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.prod"
    container_name: web
    ports:
      - '3000:3000'
    volumes:
      - .:/apps/web
      - /apps/web/node_modules